spring:
  application:
    name: my-restful-service
  #logging:
  #  level:
  #    org.springframework: DEBUG
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"