spring:
  application:
    name: my-restful-service
  #logging:
  #  level:
  #    org.springframework: DEBUG
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
#  security:
#    user:
#      name: username
#      password: password


management:
  endpoints:
    web:
      exposure:
        include: "*"